

const HomePage = () => {

    return(
        <div>
            <div>navbar</div>
            <div>navbar</div>
            <div>navbar</div>
            <div>navbar</div>
            <div>navbar</div>
            <div>navbar</div>
            <div>navbar</div>
            <div>navbar</div>
            <div>navbar</div>
            <div>navbar</div>
            <div>navbar</div>
            <div>navbar</div>
            <div>navbar</div>
            <div>navbar</div>
            <div>navbar</div>
            <div>navbar</div>
            <div>navbar</div>
            <div>navbar</div>
            <div>navbar</div>
            <div>navbar</div>
            <div>navbar</div>
            <div>navbar</div>
            <div>navbar</div>
            <div>navbar</div>
            <div>navbar</div>
            <div>navbar</div>
            <div>navbar</div>
            <div>navbar</div>
            <div>navbar</div>
            <div>navbar</div>
            <div>navbar</div>
            <div>navbar</div>
            <div>navbar</div>
            <div>navbar</div>
            <div>navbar</div>
            <div>navbar</div>
            <div>navbar</div>
            <div>navbar</div>
            <div>navbar</div>
            <div>navbar</div>
            <div>navbar</div>
            <div>navbar</div>
            <div>navbar</div>
            <div>navbar</div>
            <div>navbar</div>
            <div>navbar</div>
            <div>navbar</div>
            <div>navbar</div>
            <div>navbar</div>
            <div>navbar</div>
            <div>navbar</div>
            <div>navbar</div>
            <div>navbar</div>
            <div>navbar</div>
            <div>navbar</div>
            <div>navbar</div>
            <div>navbar</div>
            <div>navbar</div>
            <div>navbar</div>
            <div>navbar</div>
            <div>navbar</div>
            <div>navbar</div>
            <div>navbar</div>
            <div>navbar</div>
            <div>navbar</div>
            <div>navbar</div>
            <div>navbar</div>
            <div>navbar</div>
            <div>navbar</div>
            <div>navbar</div>
            <div>navbar</div>
            <div>navbar</div>
        </div>
    )
}

export default HomePage